### ISSUE TITLE
Fix formatting/spacing on results page

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#29]
![untitled](https://user-images.githubusercontent.com/7328774/29641887-99c84626-881a-11e7-8a23-d9b5e56ceaa0.png)

Fix the search facets at the top of the page for better padding/spacing.

**Comment by jechols** [comment]
Argh.  This is my fault.  I just "fixed" it in core, but clearly didn't check the spacing very closely.  I probably didn't look at it after adding labels to the fields.

I'll fix this in core and let you know when I've pulled in the fix to oregonnews-new.

**Comment by jechols** [comment]
Okay, I see the problem.  Locally my frequency list is very short since I don't have any real data.  On the live site, we have tons of data, and frequency values are very verbose (e.g., "Daily (except Sat. and Sun.)"), which stretches out that dropdown, not leaving enough room for the label.  I can fix it, but there's always the possibility of a value showing up that is even longer, blowing away the UI again.

It may be worth having the discussion on better faceting soon.  OD-like faceting could really help out ONI, I think.

**Comment by sseymore** [comment]
Ok, that sounds good. I was looking at facets on other newspaper sites (not-ONI) and enjoying them. I can find them again.

**Comment by jechols** [comment]
Okay, I've put in a temporary fix.  But we should figure out a better facet system as soon as we can.  I have no idea how long it would take to do that, so we probably need to plan for a mini-sprint of some kind.

**Comment by jechols** [comment]
@sseymore We should figure out a long-term strategy.  Maybe write up another ticket.  But for go-live, I think we're good.  If you agree, feel free to close this.

**Comment by sseymore** [comment]
I agree. This might also be a community-wide interest. Good for now.
