### ISSUE TITLE
Refine Search is not working

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#39]
Doing an advanced keyword search on one title and choosing an option in the Sort drop down on the results page and then choosing "Refine Search" is losing the newspaper selection. 

Example: Do a search for "switzler" in East Oregonian and get 405 results. Choose Date in Sort and Refine Search. All titles appear, not just East Oregonian.

I think this might be happening only when certain titles are selected.

**Comment by jechols** [comment]
I think there's a problem with the information it tries to hold onto when you refine.  I've seen the "refine" options work really well sometimes, so I don't know exactly what the problem is.

I'm hoping we can get proper faceting in place to address issues like this, because debugging the search we have today would be largely wasted once we rewrite search to accommodate good facets.

But let me know if this is something to address ASAP.

**Comment by sseymore** [comment]
#https://github.com/open-oni/open-oni/issues/213
